-- Initial schema for the tutorial's data model: categories -> products -> orders <- customers.
-- Flyway applies this migration once, in every environment (dev, test via Testcontainers, prod),
-- via a dedicated blocking JDBC connection, separate from the reactive R2DBC connection used by
-- the application at runtime. There is no ORM validating against this schema: R2DBC entities are
-- plain mapped records with no automatic relation, so this file is the single source of truth.

CREATE TABLE categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  BIGINT NOT NULL REFERENCES categories (id),
    product_name VARCHAR(255) NOT NULL,
    unit_price   REAL NOT NULL CHECK (unit_price > 0)
);

CREATE INDEX idx_products_category_id ON products (category_id);

CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    telephone  VARCHAR(50) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    address    VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers (id),
    product_id  BIGINT NOT NULL REFERENCES products (id),
    quantity    INT NOT NULL CHECK (quantity > 0),
    total       DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_product_id ON orders (product_id);
