-- Adds application users for reactive security (feature/auth). A single role column is
-- enough for the two-role authorization model this tutorial demonstrates (USER, ADMIN); a
-- full many-to-many roles table would add relational complexity R2DBC cannot resolve
-- automatically without buying any real teaching value here.

CREATE TABLE app_users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    role     VARCHAR(20) NOT NULL
);
